In [1]:
pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.3 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [3]:
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.indomaret.klikindomaret',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=10000,
    filter_score_with=None
)

In [4]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,7e8262e2-9f48-4f5c-9c1e-b5a25e8da444,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Dua kali pesan, selalu dtg terlambat. yg skrg ...",1,20,2510101,2025-10-22 05:09:17,None,NaT,2510101
1,74b19d5c-e362-4fdc-a9cb-89a0b6165b92,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"waktu saya lacak pesanan saya, tertulis disera...",2,160,2510101,2025-10-19 05:57:05,None,NaT,2510101
2,5544bdcc-9d46-4293-b297-dae9f55d4a10,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"mengecewakan sih, barang sudah 2 hari status s...",1,18,2510102,2025-10-26 14:15:32,None,NaT,2510102
3,06e1b741-edd1-4471-9f4b-347d5dd9bd46,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Selama pake aplikasi ini oke oke saja. kurirny...,5,34,2510101,2025-10-20 21:12:40,"Hi Sobat, Terima kasih ya sudah mau berbagi pe...",2024-02-13 08:42:42,2510101
4,2553d51f-789f-4a76-8a92-7e21a49c0c15,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Review jujur dari aku! ini aplikasi sangat ber...,5,4,2510102,2025-10-23 15:04:47,None,NaT,2510102

In [5]:
len(df_busu.index)

10000

In [6]:
df_busu[['userName', 'score', 'at', 'content']].head()

,userName,score,at,content
0,Pengguna Google,1,2025-10-22 05:09:17,"Dua kali pesan, selalu dtg terlambat. yg skrg ..."
1,Pengguna Google,2,2025-10-19 05:57:05,"waktu saya lacak pesanan saya, tertulis disera..."
2,Pengguna Google,1,2025-10-26 14:15:32,"mengecewakan sih, barang sudah 2 hari status s..."
3,Pengguna Google,5,2025-10-20 21:12:40,Selama pake aplikasi ini oke oke saja. kurirny...
4,Pengguna Google,5,2025-10-23 15:04:47,Review jujur dari aku! ini aplikasi sangat ber...

In [7]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [8]:
my_df.to_csv("scrapped_data_playstore_indomaret.csv", index=False)

In [9]:
!pip freeze > requirements.txt
from google.colab import files
files.download('requirements.txt')